// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Eskool.Models
{

    [Table("m_zone")]
    public  class MZone
    {
        public long? NationalId { get; set; }
        public long ZoneId { get; set; }
        [Key]
        public string ZoneCode { get; set; }
        public string ZoneName { get; set; }
        public string SapmarketCode { get; set; }
        public string Creator { get; set; }
        public DateTime? CcreationDate { get; set; }
    }
}