// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Eskool.Models
{

    public  class VmarketRegionZones
    {

        public string RegeionCode { get; set; }
        public string RegeionName { get; set; }

        [Key]
        public string MarketCode { get; set; }
        public string MarketName { get; set; }
        public string ZoneCode { get; set; }
        public string ZoneName { get; set; } 
        public string DivisionCode { get; set; }
        public string DivisionName { get; set; }       
        public int BusinessNatureID { get; set; }
        public string BusinessNatureName { get; set; }


    }




}