// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Eskool.Models
{
    public partial class VMasterCodeList
    {

        [Key]
        public string Doctormastercode { get; set; }

        public string Creator { get; set; }
        public DateTime Creationdate { get; set; }
        public string CreationdateStr { get; set; }        
        public string Name { get; set; }
        public string User_Group { get; set; }

    }
}